name = "MagicSquares"
uuid = "733919f0-fbf6-471e-a3b8-7cae3dee0e2c"
version = "0.0.1"
authors = ["Ed Scheinerman <ers@jhu.edu>"]

[deps]
ChooseOptimizer = "858a232f-1959-5553-8cfc-91e1fd5304e2"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"

[compat]
ChooseOptimizer = "0.3"
JuMP = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]